services:
  db:
    image: postgres:11-beta1-alpine
    container_name: ssoscratch-db
    environment:
      POSTGRES_DB: ssoscratch
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ssoscratch:/var/lib/postgresql/data
    ports:
      - 6432:5432

volumes:
  ssoscratch: