spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  web:
    resources:
      add-mappings: false
  jpa:
    properties:
      jakarta:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: none
              create-target: src/main/resources/db/diff.sql
  liquibase:
    enabled: false
    change-log: db/changelog.yaml
  docker:
    compose:
      enabled: false

logging:
  level:
    com:
      example: TRACE
    org:
      springframework: INFO

sso:
  issuer: ${SSO_ISSUER}
  jwks-uri: ${SSO_JWKS_URI}
  key-id: ${SSO_KEY_ID}
  private-key: ${SSO_PRIVATE_KEY}
  public-key: ${SSO_PUBLIC_KEY}

app:
  uris: ${APP_URIS:.split(",")}

