spring:
  datasource:
    url: jdbc:postgresql://localhost:6432/oauth2scratch
    username: postgres
    password: postgres
  shell:
    interactive:
      enabled: true
  jpa:
    properties:
      jakarta:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: update
              create-target: oauth2-tools/src/main/resources/db/diff.sql
  liquibase:
    enabled: false
    change-log: db/changelog.yaml